-- MySQL Script generated by MySQL Workbench
-- Sat Jan 27 16:14:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ecommerce` ;

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`about` (
  `idabout` INT(11) NOT NULL AUTO_INCREMENT,
  `paragraph1` LONGTEXT NOT NULL,
  `paragraph2` LONGTEXT NOT NULL,
  `paragraph3` LONGTEXT NOT NULL,
  `img1` VARCHAR(255) NOT NULL,
  `img2` VARCHAR(255) NOT NULL,
  `img3` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idabout`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`employe` (
  `idemploye` INT(11) NOT NULL AUTO_INCREMENT,
  `created` DATETIME NOT NULL,
  `fullname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idemploye`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`article` (
  `idarticle` INT(11) NOT NULL AUTO_INCREMENT,
  `fkemploye` INT(11) NOT NULL,
  `title` LONGTEXT NOT NULL,
  `category` ENUM('ANUNCIO', 'BLOG') NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `description` LONGTEXT NOT NULL,
  `status` ENUM('CREATE', 'ONLINE', 'OFFLINE') NOT NULL,
  `img1` VARCHAR(255) NOT NULL,
  `img2` VARCHAR(255) NOT NULL,
  `img3` VARCHAR(255) NOT NULL,
  `img4` VARCHAR(255) NOT NULL,
  `img5` VARCHAR(255) NOT NULL,
  `img6` VARCHAR(255) NOT NULL,
  `paragraph1` LONGTEXT NOT NULL,
  `paragraph2` LONGTEXT NOT NULL,
  `paragraph3` LONGTEXT NOT NULL,
  `paragraph4` LONGTEXT NOT NULL,
  `paragraph5` LONGTEXT NOT NULL,
  `paragraph6` LONGTEXT NOT NULL,
  `portada` LONGTEXT NOT NULL,
  PRIMARY KEY (`idarticle`),
  INDEX `fk_article_employe1_idx` (`fkemploye` ASC) ,
  CONSTRAINT `fk_article_employe1`
    FOREIGN KEY (`fkemploye`)
    REFERENCES `ecommerce`.`employe` (`idemploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`category` (
  `idcategory` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`company` (
  `idcompany` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `port` VARCHAR(45) NOT NULL,
  `host` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `facebook` VARCHAR(255) NOT NULL,
  `instagram` VARCHAR(255) NOT NULL,
  `tiktok` VARCHAR(255) NOT NULL,
  `whatsapp` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcompany`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`customer` (
  `idcustomer` INT(11) NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `photo` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idcustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`hero` (
  `idhero` INT(11) NOT NULL AUTO_INCREMENT,
  `slogan` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `img1` VARCHAR(255) NOT NULL,
  `img2` VARCHAR(255) NOT NULL,
  `img3` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idhero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`ordersale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`ordersale` (
  `idorder` INT(11) NOT NULL AUTO_INCREMENT,
  `fkcustomer` INT(11) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `ammount` DECIMAL(6,2) NOT NULL,
  `address` MEDIUMTEXT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` ENUM('CREATED', 'PAID', 'PAYMENT_FAILTURE', 'DISPATCHING', 'DELIVERED') NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`idorder`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) ,
  INDEX `fk_order_customer_idx` (`fkcustomer` ASC) ,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`fkcustomer`)
    REFERENCES `ecommerce`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`product` (
  `idproduct` INT(11) NOT NULL AUTO_INCREMENT,
  `fkcategory` INT(11) NOT NULL,
  `create_by` INT(11) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `img1` VARCHAR(255) NOT NULL,
  `img2` VARCHAR(255) NOT NULL,
  `img3` VARCHAR(255) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `stock` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `status` ENUM('CREATED', 'ONLINE', 'OFFLINE') NOT NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `fk_product_category1_idx` (`fkcategory` ASC) ,
  INDEX `fk_product_employe1_idx` (`create_by` ASC) ,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`fkcategory`)
    REFERENCES `ecommerce`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_employe1`
    FOREIGN KEY (`create_by`)
    REFERENCES `ecommerce`.`employe` (`idemploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`orderdetail` (
  `iddetail` INT(11) NOT NULL AUTO_INCREMENT,
  `fkorder` INT(11) NOT NULL,
  `fkproduct` INT(11) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `preference` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`iddetail`),
  INDEX `fk_order_detail_order1_idx` (`fkorder` ASC) ,
  INDEX `fk_order_detail_product1_idx` (`fkproduct` ASC) ,
  CONSTRAINT `fk_order_detail_order1`
    FOREIGN KEY (`fkorder`)
    REFERENCES `ecommerce`.`ordersale` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_product1`
    FOREIGN KEY (`fkproduct`)
    REFERENCES `ecommerce`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ecommerce`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` ENUM('EMPLOYE', 'CUSTOMER') NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created` DATETIME NOT NULL,
  `status` ENUM('ONLINE', 'UPDATE_PASS', 'OFFLINE') NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
